#Courtesy weide-zhou https://github.community/t/how-to-setup-github-actions-to-run-my-python-script-on-schedule/18335

name: fetch_daily

on:
  schedule:
    - cron: "*/5 * * * *" 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
        cache: 'pip'
    - name: Install dependencies
      run: python -m pip install --upgrade pip pandas
    - name: execute fetch script
      run: |
        python ./bin/fetch_dic.py